#!/bin/bash

WORKSPACE_DIR="${PWD}"
while [[ "${WORKSPACE_DIR}" != / ]]; do
    if [[ -e "${WORKSPACE_DIR}/WORKSPACE" ]]; then
      break;
    fi
    WORKSPACE_DIR="$(dirname "${WORKSPACE_DIR}")"
done

ARGUMENTS=$@
function contains() {
    STRING="query"
    for ARG in ${ARGUMENTS[@]}
    do
        if [ "$ARG" = "$STRING" ]; then
            return 0
        fi
    done
    return 1
}

if contains; then
    SUPPRESS_PRINTS=True
else
    SUPPRESS_PRINTS=False
fi

python ${WORKSPACE_DIR}/tools/resolve_2nd_party_repositories.py ${WORKSPACE_DIR} ${SUPPRESS_PRINTS}

exec -a "bazel-after-workspace-resolve" "${BAZEL_REAL}" "$@"