#!/bin/bash

WORKSPACE_DIR=$(pwd)
BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/\//../')
FILENAME=${WORKSPACE_DIR}/tools/2nd_party_resolved_dependencies/${BRANCH}_2nd_party_resolved_dependencies.bzl

if [ -f ${FILENAME} ]; then
    rm ${FILENAME}
fi

LOAD_THIRD_PARTIES_FILE="${WORKSPACE_DIR}/tools/load_third_parties_of_external_wix_repositories.py"

if [ -f $LOAD_THIRD_PARTIES_FILE ]; then
    export REPO_LIST=phase2
    export TRACKING_BRANCH=social-master
fi

python ${WORKSPACE_DIR}/tools/resolve_2nd_party_repositories.py ${WORKSPACE_DIR} False