load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

deps = [
    "ch.qos.logback:logback-classic:1.1.11",
    "com.codota:codota-sdk-java:1.0.11",
    "com.google.inject:guice:4.2.3",
    "com.google.inject.extensions:guice-servlet:4.2.3",
    "com.fasterxml.jackson.core:jackson-annotations:2.9.6",
    "com.fasterxml.jackson.core:jackson-core:2.9.6",
    "com.fasterxml.jackson.core:jackson-databind:2.9.6",
    "com.fasterxml.jackson.module:jackson-module-scala_2.12:2.9.6",
    "com.gitblit:gitblit:1.9.1",
    "com.github.marschall:memoryfilesystem:1.2.0",
    "com.github.pathikrit:better-files_2.12:2.17.1",
    "com.github.scopt:scopt_2.12:3.7.0",
    "com.github.tomakehurst:wiremock:2.9.0",
    "com.typesafe.akka:akka-actor_2.12:2.5.15",
    "com.typesafe.akka:akka-http-core_2.12:10.1.4",
    "com.typesafe.akka:akka-parsing_2.12:10.1.4",
    "com.typesafe.akka:akka-stream_2.12:2.5.15",
    "com.wix:http-testkit_2.12:0.1.19",
    "com.wix:http-testkit-client_2.12:0.1.19",
    "com.wix:http-testkit-core_2.12:0.1.19",
    "com.wix:http-testkit-server_2.12:0.1.19",
    "com.wix:http-testkit-specs2_2.12:0.1.19",
    "commons-codec:commons-codec:1.11",
    "commons-io:commons-io:2.6",
    "javax.servlet:javax.servlet-api:3.1.0",
    "junit:junit:4.12",
    "org.apache.maven:maven-artifact:3.5.4",
    "org.apache.maven:maven-model:3.5.4",
    "org.apache.maven:maven-model-builder:3.5.4",
    "org.apache.maven:maven-plugin-api:3.5.4",
    "org.apache.maven:maven-resolver-provider:3.5.4",
    "org.apache.maven.resolver:maven-resolver-api:1.3.3",
    "org.apache.maven.resolver:maven-resolver-connector-basic:1.3.1",
    "org.apache.maven.resolver:maven-resolver-impl:1.3.3",
    "org.apache.maven.resolver:maven-resolver-spi:1.3.3",
    "org.apache.maven.resolver:maven-resolver-transport-file:1.3.1",
    "org.apache.maven.resolver:maven-resolver-transport-http:1.3.1",
    "org.apache.maven.resolver:maven-resolver-util:1.3.1",
    "org.codehaus.mojo:mrm-api:1.1.0",
    "org.codehaus.mojo:mrm-maven-plugin:1.1.0",
    "org.codehaus.mojo:mrm-servlet:1.1.0",
    "org.codehaus.plexus:plexus-component-annotations:1.7.1",
    "org.codehaus.plexus:plexus-container-default:1.7.1",
    "org.codehaus.plexus:plexus-interpolation:1.24",
    "org.codehaus.plexus:plexus-utils:3.1.0",
    "org.eclipse.jgit:org.eclipse.jgit:4.8.0.201706111038-r",
    "org.eclipse.sisu:org.eclipse.sisu.plexus:0.3.3",
    "org.jgrapht:jgrapht-core:0.9.2",
    "org.mockito:mockito-core:2.21.0",
    "org.scala-lang.modules:scala-java8-compat_2.12:0.8.0",
    "org.scala-lang.modules:scala-xml_2.12:1.1.0",
    "org.scala-lang:scala-compiler:2.12.6",
    "org.scala-lang:scala-library:2.12.6",
    "org.scala-lang:scala-reflect:2.12.6",
    "org.scalaj:scalaj-http_2.12:2.4.1",
    "org.slf4j:slf4j-api:1.7.25",
    "org.sonatype.sisu:sisu-guice:jar:no_aop:3.1.6",
    "org.specs2:specs2-common_2.12:4.4.1",
    "org.specs2:specs2-core_2.12:4.4.1",
    "org.specs2:specs2-fp_2.12:4.4.1",
    "org.specs2:specs2-junit_2.12:4.4.1",
    "org.specs2:specs2-matcher_2.12:4.4.1",
    "org.specs2:specs2-matcher-extra_2.12:4.4.1",
    "org.specs2:specs2-mock_2.12:4.4.1",
]

def dependencies():
    maven_install(
        artifacts = deps,
        repositories = [
            "https://repo.maven.apache.org/maven2/",
            "https://mvnrepository.com/artifact",
            "https://maven-central.storage.googleapis.com",
            "http://gitblit.github.io/gitblit-maven",
            ],
        generate_compat_repositories = True,
        maven_install_json = "@exodus//:maven_install.json",
    )
