name: Run all tests

on: [push]

jobs:
  build:
    # Job name is Greeting
    name: ${{ matrix.test_script }} (${{ matrix.os }})
    # This job runs on Linux
    runs-on: ubuntu-latest
    container:
      image: l.gcr.io/google/bazel:3.5.0
    steps:
      - name: install bazelisk
        run: |
            curl -L --output /usr/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-${SYS_ENV_PLATFORM}-amd64
            chmod +x /usr/bin/bazel
            which bazel

      - uses: actions/checkout@v2

      - name: bazel cache
        uses: actions/cache@v2
        with:
          path: .bazel_cache
          key: ${{ github.ref }}
          restore-keys: |
            ${{ github.ref }}
            refs/heads/master

      - name: run bazel
        run: |
            bazel test --bazelrc=.bazelrc.remote test -k //...
